name: PR_DEPLOY
on:
  issue_comment:
    types: [created]
jobs:
  get-comment:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request }}
    steps:
      - uses: actions/checkout@v3
      - name: Get comment message
        id: comment
        run: |
          MESSAGE=$(jq --raw-output .comment.body "$GITHUB_EVENT_PATH")
          ACTION=$(echo $MESSAGE | cut -d '/' -f 1)
          ENV=$(echo $MESSAGE | cut -d '/' -f 2)
          VERSION=$(echo $MESSAGE | cut -d '/' -f 3)
          RUN_NUMBER=$(echo $MESSAGE | cut -d '.' -f 3)
          ACTION_ID=$(gh run list -w PR_BUILD --limit 100 --json number,databaseId --jq ".[] | select(.number == $RUN_NUMBER) | .databaseId")
          echo "ACTION=$ACTION" >> $GITHUB_OUTPUT
          echo "ENV=$ENV" >> $GITHUB_OUTPUT
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "RUN_NUMBER=$RUN_NUMBER" >> $GITHUB_OUTPUT
          echo "ACTION_ID=$ACTION_ID" >> $GITHUB_OUTPUT
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      ACTION: ${{ steps.comment.outputs.ACTION }}
      ENV: ${{ steps.comment.outputs.ENV }}
      VERSION: ${{ steps.comment.outputs.VERSION }}
      RUN_NUMBER: ${{ steps.comment.outputs.RUN_NUMBER }}
      ACTION_ID: ${{ steps.comment.outputs.ACTION_ID }}
  deploy:
    runs-on: ubuntu-latest
    needs: get-comment
    permissions:
      pull-requests: write

    if: ${{ needs.get-comment.outputs.ACTION == 'deploy' }}
    steps:
      - name: Deploy
        run: |
          echo "Deploying $ENV"
          echo "Version $VERSION"
      - uses: actions/checkout@v3
      - name: Download artifact
        run: |
          gh run download $ACTION_ID
          ls
          ls output
        env:
          ACTION: ${{ needs.get-comment.outputs.ACTION }}
          ENV: ${{ needs.get-comment.outputs.ENV }}
          VERSION: ${{ needs.get-comment.outputs.VERSION }}
          RUN_NUMBER: ${{ needs.get-comment.outputs.RUN_NUMBER }}
          ACTION_ID: ${{ needs.get-comment.outputs.ACTION_ID }}
