name: PR Deploy

on:
  issue_comment:
    types: [created]
jobs:
  get-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Get comment message
        id: comment
        run: |
          echo "::set-output name=MESSAGE::$(jq --raw-output .comment.body "$GITHUB_EVENT_PATH")"
          ACTION=$(echo $MESSAGE | cut -d '/' -f 1)
          ENV=$(echo $MESSAGE | cut -d '/' -f 2)
          VERSION=$(echo $MESSAGE | cut -d '/' -f 3)
          RUN_NUMBER=$(echo $MESSAGE | cut -d '.' -f 3)
          ACTION_ID=$(gh run list --json number,databaseId --jq '.[] | select(.number == $RUN_NUMBER) | .databaseId')
          echo "::set-output name=ACTION::$ACTION"
          echo "::set-output name=ENV::$ENV"
          echo "::set-output name=VERSION::$VERSION"
          echo "::set-output name=RUN_NUMBER::$RUN_NUMBER"
          echo "::set-output name=ACTION_ID::$ACTION_ID"
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      ACTION: ${{ steps.comment.outputs.ACTION }}
      ENV: ${{ steps.comment.outputs.ENV }}
      VERSION: ${{ steps.comment.outputs.VERSION }}
      RUN_NUMBER: ${{ steps.comment.outputs.RUN_NUMBER }}
      ACTION_ID: ${{ steps.comment.outputs.ACTION_ID }}
  deploy:
    runs-on: ubuntu-latest
    needs: get-comment
    permissions:
      pull-requests: write

    if: ${{ needs.get-comment.outputs.ACTION == 'deploy' }}
    steps:
      - name: Deploy
        run: |
          echo "Deploying $ENV"
          echo "Version $VERSION"

        env:
          ACTION: ${{ needs.get-comment.outputs.ACTION }}
          ENV: ${{ needs.get-comment.outputs.ENV }}
          VERSION: ${{ needs.get-comment.outputs.VERSION }}
          RUN_NUMBER: ${{ needs.get-comment.outputs.RUN_NUMBER }}
          ACTION_ID: ${{ needs.get-comment.outputs.ACTION_ID }}
