name: Feature Branch CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
        pull-requests: read
    steps:
    - uses: actions/checkout@v3
    - name: Find PR number
      run: gh pr list  --search "fdf7dc2a13f90e9b48ce40a64e330e260a7d637d"  --state open --json "title,url,number" --template '{{range .}} PR_URL={{.url}}{{"\n"}} PR_NUMBER={{.number}}{{"\n"}} PR_TITLE={{.title}} {{end}}' | xargs -I {} echo {} >> $GITHUB_ENV
      env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: ENV
      run: env
  comment:
    runs-on: ubuntu-latest
    needs: lint
    permissions:
        pull-requests: write
    steps:
    - uses: actions/checkout@v3
    - name: Comment
      run: |
        echo "PR_URL=$PR_URL"
        echo "PR_NUMBER=$PR_NUMBER"
        echo "PR_TITLE=$PR_TITLE"
        gh pr comment $PR_NUMBER -b "Hello World"