name: Feature Branch CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Find PR number
      run: gh pr list  --search "fdf7dc2a13f90e9b48ce40a64e330e260a7d637d"  --state open --json "title,url,number" --template '{{range .}} PR_URL={{.url}}{{"\n"}} PR_NUMBER={{.number}}{{"\n"}} PR_TITLE={{.title}} {{end}}' | xargs -I {} echo {} >> $GITHUB_ENV

    - name: ENV
      run: env