name: Feature Branch CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: pull_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH") && echo pull_number=$pull_number >> $GITHUB_ENV
    - run: env